apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: node-maintenance-operator-webhook-service
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    name: node-maintenance-operator
status:
  loadBalancer: {}
